USE [master]
GO

/****** Object:  Database [Analisis_De_Ventas_AWDW]    Script Date: 11/29/2025 12:39:44 PM ******/
CREATE DATABASE [Analisis_De_Ventas_AWDW]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Analisis_De_Ventas_AWDW', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Analisis_De_Ventas_AWDW.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Analisis_De_Ventas_AWDW_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Analisis_De_Ventas_AWDW_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Analisis_De_Ventas_AWDW].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Analisis_De_Ventas_AWDW] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Analisis_De_Ventas_AWDW] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Analisis_De_Ventas_AWDW] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Analisis_De_Ventas_AWDW] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Analisis_De_Ventas_AWDW] SET ARITHABORT OFF 
GO

ALTER DATABASE [Analisis_De_Ventas_AWDW] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Analisis_De_Ventas_AWDW] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Analisis_De_Ventas_AWDW] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Analisis_De_Ventas_AWDW] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Analisis_De_Ventas_AWDW] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Analisis_De_Ventas_AWDW] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Analisis_De_Ventas_AWDW] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Analisis_De_Ventas_AWDW] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Analisis_De_Ventas_AWDW] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Analisis_De_Ventas_AWDW] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Analisis_De_Ventas_AWDW] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Analisis_De_Ventas_AWDW] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Analisis_De_Ventas_AWDW] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Analisis_De_Ventas_AWDW] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Analisis_De_Ventas_AWDW] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Analisis_De_Ventas_AWDW] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Analisis_De_Ventas_AWDW] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Analisis_De_Ventas_AWDW] SET RECOVERY FULL 
GO

ALTER DATABASE [Analisis_De_Ventas_AWDW] SET  MULTI_USER 
GO

ALTER DATABASE [Analisis_De_Ventas_AWDW] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Analisis_De_Ventas_AWDW] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Analisis_De_Ventas_AWDW] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Analisis_De_Ventas_AWDW] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Analisis_De_Ventas_AWDW] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Analisis_De_Ventas_AWDW] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Analisis_De_Ventas_AWDW] SET QUERY_STORE = ON
GO

ALTER DATABASE [Analisis_De_Ventas_AWDW] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [Analisis_De_Ventas_AWDW] SET  READ_WRITE 
GO
